### ISSUE TITLE
Calendar selection options unavailable

### ISSUE THREAD

**Issue by DRCHRIS2** [hidadev/musicrecitals.hida.asu.edu#4]
On the default New Reservation page, available dates for venues are not returning to the interface to be allowed for selection:
![capture2](https://user-images.githubusercontent.com/20821943/26837897-6f9bb14a-4a93-11e7-96b8-39ed3a0f9f1c.PNG)

(This is from https://hida-lw12.hida.asu.edu/reservations.php?forceform=1)
However, the current production environment is showing dates available for selection for the venues - https://musicrecitals.hida.asu.edu/reservations.php?forceform=1

**Comment by khushipatel0301** [comment]
![image](https://user-images.githubusercontent.com/22405790/27342256-7959434e-5594-11e7-8443-9fe62fa86123.png)
